openzim/warc2zim

- src/warc2zim/main.py
Commit a777d080 broke indexing of HTML articles by limiting indexing to HTML mime-types
(goal was to stop indexing everything) but that didn't account for the fact that we
changed the mime to octet-stream for other reasons
> Fixed indexing on HTML articles

- README.md
- src/warc2zim/main.py
- tests/test_warc_to_zim.py
- name flags: use --name, --zim-file, --output convention for output, per spec in #4
- use zstd compression (#49)
- add codefactor badge to README (#14)
- update README with more info on domain filtering
- tests: use tmp_path fixture for temp dir
> flag improvements and docs:

- src/warc2zim/main.py
> [bugfix] improved exception handling in parse_title

- src/warc2zim/content_rewriting/css.py
- src/warc2zim/content_rewriting/html.py
- src/warc2zim/converter.py
- src/warc2zim/items.py
- src/warc2zim/url_rewriting.py
- tests/test_css_rewriting.py
- tests/test_html_rewriting.py
- tests/test_js_rewriting.py
- tests/test_url_rewriting.py
Fixes #137 
With this PR we don't rewrite html (`a href`) link when the url is not in the warc archive.
Other links are always rewritten to avoid zim file silently phoning home.
> Handles external links (without SW)

- src/warc2zim/content_rewriting/html.py
- tests/test_html_rewriting.py
> Do not crash when html is malformed and doesn't contains a actual sytle.

- src/warc2zim/converter.py
- tests/test_warc_to_zim.py
We don't use service working with warc2zim2.
> Remove tag `_sw:yes`

- src/warc2zim/content_rewriting/ds.py
- src/warc2zim/content_rewriting/generic.py
- src/warc2zim/content_rewriting/js.py
- src/warc2zim/content_rewriting/rx_replacer.py
- src/warc2zim/items.py
Some js coming from specific website need to be patched to work "offline".
This patching is made using a set of specific regex to "activate" depending of path.
Sadly, there is no test because there is none in wabac.js (the source of the rules set) and
I don't know want/how to test.
We probably have more to import from wabac.js, but this PR is a fix to #149
> Introduce generic Rewriter dispatching between specific rewriters.

- src/warc2zim/__about__.py
- src/warc2zim/converter.py
- src/warc2zim/main.py
- tests/test_warc_to_zim.py
Fix #156 
Nota: also updates the version to `dev1` as agreed in issue.
> Allow to specify a scraper suffix for the ZIM scraper metadata at the CLI

- CHANGELOG.md
- src/warc2zim/__about__.py
- src/warc2zim/converter.py
- tests/test_warc_to_zim.py
Logs were speaking about `error code 100`, which indicates that args are OK for warc2zim.
I changed this to `return code 100` since it is the proper term and the wrong term was frequently misleading the content team into believing there was an error.
> Enhance wording about return code

- src/warc2zim/url_rewriting.py
- tests/test_url_rewriting.py
Fix #167
Spec is explicit about that, we can have space around url: https://www.w3.org/TR/2014/REC-html5-20141028/infrastructure.html#valid-url-potentially-surrounded-by-spaces
> String leading and trailing space from url.

- pyproject.toml
- src/warc2zim/__about__.py
- src/warc2zim/content_rewriting/css.py
- src/warc2zim/content_rewriting/rx_replacer.py
- tests/test_css_rewriting.py
- tests/test_html_rewriting.py
- tests/test_js_rewriting.py
- tests/utils.py
Return the original content if we cannot parse the css.
---
In case of invalid css tinycss2 doesn't not failed on parsing, but generate a ParserError token
https://doc.courtbouillon.org/tinycss2/stable/api_reference.html?highlight=parser#tinycss2.ast.ParseError
This is on serialization that exception occurs.
We even try/except all transformation to be sure.
Fix #155
> Be more tolerant to invalid css.

- pyproject.toml
- src/warc2zim/content_rewriting/generic.py
- src/warc2zim/content_rewriting/html.py
- src/warc2zim/url_rewriting.py
- src/warc2zim/utils.py
- tests/test_utils.py
- tests/test_warc_to_zim.py
This PR try to detect encoding using 3 methods:
- From http headers in the warc record
- From encoding declaration inside the content
- From statistical analysis of the content (made by chardet)
Fix #177
> Correctly detect encoding and decode bytes 

- src/warc2zim/content_rewriting/generic.py
See suggestion in #186 about better error message.
> Better Exception, with item's path, when we cannot decode the content.

- src/warc2zim/content_rewriting/css.py
- src/warc2zim/content_rewriting/ds.py
- src/warc2zim/content_rewriting/generic.py
- src/warc2zim/content_rewriting/html.py
- src/warc2zim/content_rewriting/js.py
- src/warc2zim/content_rewriting/rx_replacer.py
- tests/test_html_rewriting.py
Inline json was rewriten as javascript. Now we rewrite it as json.
This PR also rewrite "plan" json file with domain specific rules and rewrite "jsonp" (json callback) content.
This two fixes come from wabac rewriting but don't seems to be necessary (at least for this fix) and are not tested.
You can find a mdn archive converted to zim using this PR at https://tmp.kiwix.org/ci/test-warc/mgautier/mdn_json.zim
Ping @jaifroid
Fix #181
Fix #160
> Correctly rewrite json.

- src/warc2zim/converter.py
- tests/test_warc_to_zim.py
Fix #197 
`add_items_for_warc_record` is already called only for records of type `resource`, `response` and `revisit` (i.e. `request` records are ignored) due to the filtering logic of `iter_warc_records`.
The logic to add a real item to the ZIM was not called if record type is `revisit`, i.e. it was called only for `resource` and `response`. 
As explained in #197, `resource` WARC records must not be added as-is to the ZIM, they are not regular web responses (as their WARC type implies).
The logic is hence inverted to also be future-prood:
- apply the default logic to add an item to the ZIM only if record is a `response`
- apply the logic to compute revisits only if record is a `revisit`
> Ignore `resource` WARC records for now

- src/warc2zim/url_rewriting.py
- tests/test_fuzzy_rules.py
Lookbehind (https://caniuse.com/?search=Lookbehind) is not fully supported on "old" browsers.
But lookahead (https://caniuse.com/?search=Lookahead) is supported "everywhere" as it is part of original js regular expression.
The tricky part in this change is that we must match the `?` both as:
- Just after `videoplayback` (always)
- Potentially just before `id=...`.
Fix #174 
Ping @jaifroid
> Use Lookahead expression in fuzzy rules instead of Lookbehind

- pyproject.toml
Fix #207 
Changes:
- include all `statics` files as artifacts for the wheel
Nota:
- the sdist still doesn't contain the `wombat.js` which is great
> Add wombat.js back

- pyproject.toml
https://github.com/openzim/warc2zim/pull/201 forgot to remove the now useless hatchling dev dependency.
> Remove useless hatchling dependency now that we are using hatch-openzim

- README.md
- docs/functional_architecture.md
- docs/software_architecture.md
- docs/technical_architecture.md
- pyproject.toml
Changes:
- create a high level documentation of the scraper
I've left multiple `**TODO**` where I need your help if possible (especially @mgautierfr) to resolve the situation.
The exercise was (as expected by all of us) very interesting to discover areas for improvements:
- probably unused Python libraries
- potentially useless transformations (JSON, JSONP and static JS url rewriting, all these are done dynamically by wombat as far as I've understood)
I'm waiting for your feedback on these last points and will add more test cases to the test website around these topics in the mean time.
> Architecture documentation

- CHANGELOG.md
- src/warc2zim/converter.py
- tests/test_warc_to_zim.py
This PR adds a check for invalid zim filenames. This check works by creating a temporary file with the name provided and deletes it immediately. If an exception is thrown, the program logs it and exits.
Fixes #232
> Add check for invalid zim file names

- src/warc2zim/url_rewriting.py
- tests/test_warc_to_zim.py
Fix #247 
- all URL rewriting issues are simply logged, but they do not cause the scraper to fail
- no more special handling of hostname rewriting issues
- try to decode hostname only if it starts with "xn--" (the indicator used for IDNA puny-encoded see [here](https://web.archive.org/web/20100427154004/http://www.atm.tut.fi/list-archive/ietf-announce/msg13572.html))
> No more failure due to url rewriting issue

- src/warc2zim/converter.py
- src/warc2zim/utils.py
Fix #254 
- log unexpected (not an HTTPStatus) WARC record status code at WARNING log level (instead of DEBUG)
- `get_status_code` always return a value as intelligible as possible (i.e. an int value when we fail to convert it to HTTPStatus but is still an int) => useful for logs typically
- simplify `status_code_is_processable_redirect` by removing the repetition between `is_redirection` and the list of redirect codes we want to handle
> Log unexpected WARC record status codes as warnings

- src/warc2zim/content_rewriting/generic.py
- src/warc2zim/utils.py
- tests/test_utils.py
Fix #221 
Changes:
- decoding of binary WARC content:
- do not try all chardet suggested encodings in a row, but only the most probable one
- if all alternatives to decode have failed, try to simply ignore bad characters when decoding with original encoding indicated in HTTP headers
- log a warning (with details) when encoding used is not the encoding indicated in HTTP headers or characters had to be ignored
> Revisit decoding of documents from binary to string

- src/warc2zim/content_rewriting/generic.py
- src/warc2zim/converter.py
- src/warc2zim/items.py
- tests/test_warc_to_zim.py
Fix #263 
Changes:
- Fix and simplify custom CSS injection
- Pass the HTML code for CSS injection as stuff to be rendered (we need to compute the relative ZIM path based on current page location)
- directly create a ZIM record instead of faking a WARC record (simplification and less error-prone)
- store custom CSS at `_zim_static/custom.css` instead of magic URL `warc2zim.kiwix.app/custom.css`
- Not related to #263 but a slight enhancement of https://github.com/openzim/warc2zim/pull/260 changes: do not log issues about encoding when only concern is that no content-type was passed in HTTP headers
> Fix inclusion of custom CSS in warc2zim2

- README.md
- src/warc2zim/content_rewriting/html.py
- test-website/content/index.html
- test-website/content/onxxx.html
- tests/test_html_rewriting.py
Fix #209 
Changes:
- add support for onxxx events, with same logic as wabac (https://github.com/webrecorder/wabac.js/blob/main/src/rewrite/html.js#L143-L145)
- add few test cases on test website for onclick HTML events
- fix a test which was failing due to a previously introduced trick
> Add support for onxxx HTML events

- src/warc2zim/converter.py
- src/warc2zim/main.py
- tests/test_metadata_validation.py
Fix #235 
Changes:
- Validate title, description, long_description and tags early, including during the pre-check call from zimit
- Add `--disable-metadata-check` CLI argument, not intended to be exposed in Zimfarm
> Validate ZIM metadata early

- rules/rules.json
- tests/test_fuzzy_rules.py
Fix #262 
Changes:
- new fuzzy rule for youtube thumbnails
- pattern has been slightly enhanced compared to the one suggested in issue to support any file extension
> Fix youtube thumbnails

- src/warc2zim/url_rewriting.py
- test-website/content/href-to-folder/index.html
- test-website/content/index.html
- tests/test_url_rewriting.py
Fix #277 
Changes:
- Do not statically rewrite URLs composed of just a fragment (dynamic rewrite in JS is already OK)
- Add a test case to the test website with this situation and few others around the use of a folder as last portion of the URL instead of a filename
> Do not rewrite URLs composed of just a fragment

- javascript/test/fuzzyRules.js
- rules/rules.json
While fuzzy rule is working well in Python, trailing characters after the `?` from the querystring are not removed in Javascript causing the fuzzy rewriting to be incorrect.
E.g. `'i.ytimg.com/vi/-KpLmsAR23I/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgTyg-MA8=&rs=AOn4CLDr-FmDmP3aCsD84l48ygBmkwHg-g` is transformed into `i.ytimg.com.fuzzy.replayweb.page/vi/-KpLmsAR23I/thumbnail.jpgsqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgTyg-MA8=&rs=AOn4CLDr-FmDmP3aCsD84l48ygBmkwHg-g` instead of `i.ytimg.com.fuzzy.replayweb.page/vi/-KpLmsAR23I/thumbnail.jpg`
This PR fixes the situation by updating the fuzzy rules and adding a minimal test set in Javascript.
Long term solution to test all fuzzy rules in JS is described in #284
> Fix fuzzy rule for Youtube thumbnails in JS

- javascript/src/wombatSetup.js
In some occasions, url passed to JS rewriting function is an object instead of a string, causing problems like https://github.com/openzim/zim-requests/issues/1011#issuecomment-2135505415
> JS URL rewriting: take into account that url might be an object

- src/warc2zim/content_rewriting/html.py
- tests/test_html_rewriting.py
Fix #283 
Changes:
- Add support for application/javascript and text/javascript
- Fix support for application/json
- Add support for all unknown script types: do not rewrite at all (instead of assuming it is JS-classic)
- Move javascript test to proper isolated test method + add more tests
> Fix handling of <script> type in HTML documents

- CHANGELOG.md
- src/warc2zim/content_rewriting/html.py
- tests/test_html_rewriting.py
Fix #298 
Since the JS and CSS scripts are rewritten, integrity checks are failing on purpose. Since we do not really need these integrity checks, we just drop the attribute when rewritting the HTML.
Edit:
We do it for both <script> and <link> tags, because both are allowed to use this attribute
> Drop integrity attribute in HTML `<script>` and `<link>` tags

- src/warc2zim/content_rewriting/generic.py
- tests/test_rewriting.py
Fix #301 
Changes:
- revisit decode of WARC content from bytes to string
- only HTML content was benefiting from automatic encoding detection. 
- CSS used custom tinycss detection method
- now, all content type (HTML, JS, CSS and JSON) use the same automatic encoding detection.
- add test cases around handling of encoding by the generic rewriter
> Use same automatic encoding detection for all contents

- src/warc2zim/converter.py
- src/warc2zim/language.py
- tests/test_language.py
Fix #300 
Changes:
- isolate method to parse language received either from input (CLI) args or automatically retrieved from HTML metadata
- add unit testing on this method
- add support for a list of languages, permissive to spaces which will be trimmed and preserving list of languages order
- add validation of language metadata, including early validation if the lang comes from input (CLI) args
- add a real fallback to `eng` as indicated in usage, wasn't done when no lang was provided at CLI and no lang was found in WARC records
> Add support for multiple ZIM langs + validate Language metadata

- .pre-commit-config.yaml
- openzim.toml
- pyproject.toml
- src/warc2zim/content_rewriting/generic.py
- tests/test_warc_to_zim.py
Changes:
- upgrade dependencies before release
- fix return value of `get_rewrite_mode` when mode is retrieved based on new `WARC-Resource-Type` header
- including a test checking that resources have been really rewritten, to catch this bug
- javascript and JSON resources can also have `xhr` as `WARC-Resource-Type`
> Upgrade deps + fix rewrite mode

- src/warc2zim/content_rewriting/generic.py
Fix #313 
Nota: there is no additional test because I failed to reproduce the issue with the crawler. In general, PDFs are retrieved with Direct Fetch by the crawler, and in such a case we do not have the `WARC-Resource-Type` header. 
This also explains why I did not encountered this situation during my tests before 2.0.1 release. 
Under some condition Direct Fetch is not used by the crawler ... and we obviously encountered the situtation in production.
> Use mimetype to selectively rewrite only html documents

- CHANGELOG.md
- src/warc2zim/content_rewriting/generic.py
- src/warc2zim/converter.py
- src/warc2zim/items.py
- src/warc2zim/main.py
- src/warc2zim/utils.py
- tests/test_rewriting.py
- tests/test_utils.py
Fix #318 
Changes:
- add the two options mentioned in issue and use them to ignore automatically detected charsets
- add missing CHANGELOG entries from previous PRs
> Add option to ignore charsets found automatically

- CHANGELOG.md
- src/warc2zim/content_rewriting/generic.py
- src/warc2zim/converter.py
- src/warc2zim/items.py
- src/warc2zim/main.py
- src/warc2zim/utils.py
- tests/test_rewriting.py
- tests/test_utils.py
Fix #320 
To be reviewed / merged after #319
> Add option to specify content header length

- CHANGELOG.md
- docs/technical_architecture.md
- src/warc2zim/content_rewriting/generic.py
> Fix logic of rewrite mode computation for cases raised in #326

- CHANGELOG.md
- src/warc2zim/converter.py
- src/warc2zim/main.py
- tests/test_converter.py
Fix #360 
Changes:
- compute and sort the list of WARC files at converter startup, so that it is done only once no matter the number of times `iter_warc_records` is called
- log total number of WARC files
> Properly sort WARC files and log total number of WARCs found

- CHANGELOG.md
- javascript/src/wombatSetup.js
- javascript/test/wombatUrlRewriting.js
- src/warc2zim/url_rewriting.py
- tests/test_warc_to_zim.py
Fix #316 
Changes:
- in Python and in JS, when we compute the ZIM path from a given URL, we replace all multiple occurences of `/` character by a single `/`
- both rely on a utility function which is not public, since not meant to be reused anywhere else is the codebase
- in Python test, compare `ZimPath` value instead of comparing object, from better pytest report in case of issue (string are compared char by char and error is quickly spotted)
> Remove double slash in URLs, both in Python and JS

- CHANGELOG.md
- src/warc2zim/converter.py
- src/warc2zim/utils.py
Might have been a solution to #332 but not (see next comment)
NOTA : there is no test because I failed to find under which conditions we can have a non HTTP(S) WARC record + we should test for all places where we iterate on WARC records, which makes it even harder to test
> Ignore non HTTP(S) WARC records

- src/warc2zim/content_rewriting/__init__.py
- src/warc2zim/content_rewriting/html.py
- tests/conftest.py
- tests/test_html_rewriting.py
Fix #305 
Idea: we should be able to define individual rewriting rules with functions and decorators, just like we do when defining endpoints in FastAPI. We have one decorator per kind of modification: drop attribute, rewrite attribute, rewrite data (and maybe others) and we implement one decorated function per kind of modifications expected.
Changes:
- new HTMLRewritingRules class with decorators `drop_attribute` (to decide to drop an HTML tag attribute), `rewrite_attribute` (to rewrite a given HTML tag attribute - name + value), `rewrite_tag` (to rewrite the whole HTML tag, potentially dropping it completely or changing tag name), `rewrite_data` (to rewrite HTML tag data)
- an instance of this class is wired in the html rewriting logic to properly process HTML code
- new tests are added …
> Refactor HTML rewriter class to make it more open to change and expressive

- CHANGELOG.md
- src/warc2zim/content_rewriting/html.py
- test-website/content/http-equiv-redirect.html
- test-website/content/index.html
- tests/conftest.py
- tests/test_html_rewriting.py
Fix #237 
Changes:
- properly rewrite redirect target url when present in `<meta>` HTML tag
- add test case in test website
Nota: this is built on-top of https://github.com/openzim/warc2zim/pull/343 and should hence be reviewed only once this is reviewed/merged
> Correctly rewrite target url in HTML meta http-equiv redirect

- CHANGELOG.md
- pyproject.toml
- src/warc2zim/converter.py
- tests/test_warc_to_zim.py
Fix #358 
Fix #357 
Changes:
- in addition to changes needed by issues mentioned, we stop to filter warc records by type in the `iter_warc_records` generator since this is both confusing + needless ; selecting proper record type is the "using code" responsibility
and needs might vary
> Source more ZIM metadata from WARC files

- CHANGELOG.md
- Dockerfile
- pyproject.toml
- src/warc2zim/converter.py
- src/warc2zim/items.py
- src/warc2zim/language.py
- tests/test_warc_to_zim.py
Fix #148 
Fix #290 
Fix #289 
Changes:
- add SVG support for favicon
- consider PDF entries as front article just like HTML
SVG support tested manually with success on https://www.solidarite-numerique.fr/ main page
> Add support for SVG favicon + upgrade to scraperlib 4.0.0 (support auto PDF indexing)

- CHANGELOG.md
- src/warc2zim/content_rewriting/html.py
This PR replaces https://github.com/openzim/warc2zim/pull/371 with another approach based on `@lru_cache`
Fix https://github.com/openzim/warc2zim/issues/370
Changes:
- use `@cache` (an `@lru_cache` without max size since we want to cache all values) to cache rewriting rule function signature
> Cache HTML rewriting function signature

- CHANGELOG.md
- javascript/package.json
- javascript/yarn.lock
- openzim.toml
- pyproject.toml
> Upgrade deps, especially wombat 3.8.0

- CHANGELOG.md
- javascript/src/wombatSetup.js
- javascript/test/wombatSetup.js
- openzim.toml
Fix #293 
Fix #239 
Fix #333 
Changes:
- `isSW` is set to `false`, as recommended by Ilya in https://github.com/webrecorder/wombat/issues/155#issuecomment-2183191941
- `enable_auto_fetch` is set to `false` (not used anyway in our use of wombat, but setting this to `true` is a bit misleading)
- upgrade wombat to 3.8.6
~~Main concern with merging this is that this breaks the Youtube player, so we should probably wait for a solution to #333~~ => solved in wombat 3.8.4 which is part of this PR
~~Other concern is that is #327 is still not solved by this PR~~ => this is a distinct and way more tricky problem, especially in terms of implementation
> Document wombat settings and change wombat mode to fix major issue of MDN ZIM

- CHANGELOG.md
- src/warc2zim/converter.py
- test-website/Caddyfile
- test-website/Dockerfile
- test-website/content/double-slash.html
- test-website/content/index.html
> Stop checking main entry processability when it is already found

- CHANGELOG.md
- src/warc2zim/main.py
- src/warc2zim/utils.py
- tests/test_utils.py
By providing a default map of "bad" encoding aliases to standard encoding names, the scraper can continue to decode the input without failing on encountering such aliases. This PR resolves #416 
Also, aliases provided via `--encoding-aliases` are converted to lowercase, thus making them case insensitive. This resolves #412 
- Add a dictionary of default encoding aliases
- Provide method to retrieve an encoding method by alias as it simplifies testing without accessing the ENCODING_ALIASES directly.
- Make aliases to `--encoding-aliases` case insensitive.
> provide default encoding aliases
