openzim/warc2zim

src/warc2zim/main.py, src/warc2zim/templates/404.html, src/warc2zim/templates/load.js, tests/test_warc_to_zim.py
404 template: hide toolbar always, not just in top frame, fixes #52
index template: redirect without scheme, hopefully fixes #45
=> tags: add default tags (_ftindex:yes;_category:other;_sw:yes) fixes #51

src/warc2zim/main.py
Adds new formatting from black 20.8b1
=> Add new black formatting

src/warc2zim/locale/fr/LC_MESSAGES/messages.po, src/warc2zim/templates/404.html, src/warc2zim/templates/index.html, src/warc2zim/templates/load.js
=> Better missing service worker error page

README.md, src/warc2zim/main.py, tests/test_warc_to_zim.py
- new --custom-css option taking a path or a URL
- converted to a WARC record on a fixed URL: https://warc2zim.kiwix.app/custom.css
- stylesheet link added at very end of head for every HTML article
Fixes #61 
Reviewers: look at second commit only; first one is code-formatting
=> Add support for --custom-css

requirements.txt, src/warc2zim/main.py, tests/test_warc_to_zim.py
- Kept articles in A/ and headers in H/ but those are now path prefix and not namespaces
- Renamed “article” to “item” where it made sense
=> Use libzim7 API

README.md
Fix #126 
Changes:
- fix documentation about URL filtering
- fix wrong titles levels
=> Fix url filtering doc

setup.py
In commit 15567179 we have changed the function name to `main`.
=> Fix entry_points.

setup.py, src/warc2zim/content_rewriting/__init__.py, src/warc2zim/content_rewriting/css.py, src/warc2zim/content_rewriting/html.py, src/warc2zim/content_rewriting/js.py, src/warc2zim/converter.py, src/warc2zim/items.py, src/warc2zim/statics/__wb_module_decl.js, src/warc2zim/statics/wombat.js, src/warc2zim/templates/head_insert.html, src/warc2zim/url_rewriting.py, tests/test_css_rewriting.py, tests/test_html_rewriting.py, tests/test_js_rewriting.py, tests/test_warc_to_zim.py, tests/utils.py
Next step in our warc2zim2 branch : Rewrite js content (statically and dynamically)
Now, we should be able to have dynamic websites (including "complex" js to work).
Fix #136
=> Add js rewriting and wombat.

src/warc2zim/converter.py, src/warc2zim/items.py, src/warc2zim/statics/wombat_setup.js, src/warc2zim/templates/head_insert.html, src/warc2zim/templates/wombat_setup.js, src/warc2zim/url_rewriting.py, tests/test_warc_to_zim.py
No real functional change. Only code polishing.
Edit: Important code polishing, we now have removed the duplicated definition of fuzzy rules.
=> Better/Simple(/Stronger) wombat setup.

src/warc2zim/converter.py, tests/test_warc_to_zim.py
=> Fix scraper suffix

CHANGELOG.md, src/warc2zim/main.py
Resolves #150
Updated publisher metadata from 'Kiwix' to 'openZIM' in main.py
=> Update publisher metadata from 'Kiwix' to 'openZIM'

tests/test_fuzzy_rules.py
Add way more tests around fuzzy rules.
This is preparatory work for the new normalisation of URLs (#206)
=> More fuzzy tests

CHANGELOG.md, src/warc2zim/converter.py, tests/test_warc_to_zim.py
=> Enhance checks regarding availability of `output` folder

src/warc2zim/content_rewriting/html.py, src/warc2zim/content_rewriting/js.py, src/warc2zim/url_rewriting.py, tests/conftest.py, tests/test_html_rewriting.py
=> Properly notify JS module location when a base href is configured

src/warc2zim/content_rewriting/generic.py
=> Quote path passed to dynamic JS rewriting for prefix computation

README.md, tests/test_html_rewriting.py
Fix #219 (only documentation and tests needed)
=> Document and test limitations around processing of HTML attributes

README.md, src/warc2zim/converter.py, src/warc2zim/main.py
=> Simplify debugging of WARC record processsing issues

src/warc2zim/content_rewriting/generic.py, src/warc2zim/converter.py, src/warc2zim/items.py
=> Fix path typing in `WARCPayloadItem` and `Rewriter`

README.md
=> Document scraper capabilities and limitations

src/warc2zim/converter.py
Fix #246 
Changes:
- do not consider redirections to same ZimPath as something to be processed (e.g. redirecting from http://www.kiwix.org to https://www.kiwix.org is "de-facto" handled in the ZIM since there is only one ZimPath for both URLs)
- still detect redirection to same ZimPath in the while loop to avoid dead loops running forever
- more properly handle the case of a nested redirection loop ( A -> B -> A ) by displaying a clear warning and not adding anything inside the ZIM
- add more logs for easier analysis with debugging the code
=> Avoid and detect redirection loops

CHANGELOG.md, src/warc2zim/content_rewriting/html.py, tests/test_html_rewriting.py
=> Set correct charset in HTML documents

CHANGELOG.md, src/warc2zim/converter.py
Just a small debug log to help diagnosis
=> Add debug log for items whose content is empty

CHANGELOG.md, rules/rules.yaml
Fix #342 
Fix #330
NOTA: must be reviewed after https://github.com/openzim/warc2zim/pull/348 is merged
=> New fuzzy rules for various websites

CHANGELOG.md, rules/rules.yaml
=> Add fuzzy rule for iranwire questions

pyproject.toml
Needed to made a new scraperlib rc3 to use latest wombat version
=> Use scraperlib 5.0.0rc3

.pre-commit-config.yaml, CHANGELOG.md, Dockerfile, contrib/cleanup_log.py, contrib/html_convert.py, contrib/marxists.org.py, pyproject.toml, src/warc2zim/constants.py, src/warc2zim/converter.py, src/warc2zim/items.py, src/warc2zim/rewriting.py, tests/test_utils.py, tests/test_warc_to_zim.py
Upgrade dependencies (especially Python 3.13) and fix associated new linter / type checker issues
=> Upgrade dependencies - Python 3.13

.pre-commit-config.yaml, CHANGELOG.md, pyproject.toml
~~WIP: waiting for zimscraperlib 5.1.1 release~~
=> Upgrade dependencies especially zimscraperlib 5.1.1
